name: Re-build on jackson-databind v2 push
on:
  repository_dispatch:
    types: [jackson-databind-pushed]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Do we want wide matrix build? For now, limited
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '17', '21']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: 2.x
    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp clean verify

# No recursive rebuild (yet?)
